### ISSUE TITLE
Backup.

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#135]
Andy,
This may be a Dan P. issue, but my understanding is that our server has no backup, which means that all data will be lost if there is an event. Is this an issue that we can address?
Best,
John C.

**Comment by acavanagh** [comment]
Hi - this is a Dan P issue, but it's not quite the issue that it sounds
like it is.  Double check with Dan, but my understanding is that right now
your server does get backed up - weekly or daily, I'm not sure which.
That's great, it means that you're safe from utter disaster.  The problem
is that it's a backup for the whole server - it's not easy and maybe not
even possible to restore just one site without rolling back the whole
server to the most recent backup.  That means that if site A has a problem
with their database and needs to roll back, you can't do that without also
rolling back sites B-Z.  You MIGHT be able to roll the backup out on a
different server and just copy over the files you need, but I'm not
familiar enough with how these backups work to know if that's possible.

I would recommend setting up a backup scheme that copies each site's
database and images folders into separate directories (one for each site).
Ideally these folders would be on another disk - either a server or a
storage system like S3 - but since you've got your big backup for disaster
recovery, it would probably be ok to store these backups locally.  That way
if site A accidentally deletes a page after they spent 2 days writing copy
for it, or accidentally deletes an image they need, or their database
somehow gets corrupted, Dan can easily restore it just for that site
without any crazy shenanigans.  This is a Dan P job though, and he'll be
more familiar with the options and best practices than I am.  I could help
by letting him know where the assets that need to get backed up
individually are located within each site's folder.

**Comment by meetinghouse** [comment]
Thanks, Andy,

Will fwd to Dan P.


Cordially,

John Corbett
Corbett Research Group
"Building Websites That Work, for the Building Artisans"
http://www.restorationtrades.com

Publishers of:
The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

Email:  John@RestorationTrades.com
Phone: 413-586-4748
