### ISSUE TITLE
Dark Theme: Blog Post tag bugs

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#182]
In the process of creating and editing blog posts for client site shconstruction2 (dark theme), several issues that are more or less bugs have cropped up:
1. There are quite a few tags created. There are so many that the tag list in the left nav bar overflows the screen, but you can't scroll to the bottom, so the tags at the bottom (as well as the create post button, when logged) are not accessible.
2. Tags that have no posts assigned them are still showing up in the nav. For instance, "Foundations and Waterproofing" isn't being used for any of the posts, so it should drop out of the tag list. This problem was mentioned in Issue #170 also.
3. Possibly most problematic, some tags that are showing up in the tags list AND have posts tagged with them, don't show any posts when you click on them. For instance, the post "Waterproofing Fieldstone Foundation Walls" is assigned the tag "Foundations + Waterproofing." But when you click on "Foundations + Waterproofing" in the tags list, no posts come up. Other tags seem to be working fine and you see posts when you click on them (for instance, the tag "Building Design" pulls up several posts, as it should.)

**Comment by acavanagh** [comment]
Pretty sure that I've got 1 + 2 sorted out.  #3 is an issue with the plus sign.  I didn't realize this, but the browser interprets the plus sign as a spaced, so it doesn't match the tag.  Almost any other character would be fine there, including &.  I'll see if I can find a work around for that asap.

**Comment by acavanagh** [comment]
I looked more into #3; there's not a great way to allow + signs in the url.  The best option is to change the tags to use & instead and put something in the help documents.  If that's not possible I can put in something that replaces three spaces with a plus sign, since the browser reads a + as an extra space so a tag like 'Foundations + Waterproofing' would translate to 'Foundations   Waterproofing'.  That's going to break if there's no spaces, and could cause all kinds of other problems.  Really, we should just not allow anything other than alpha numeric characters in tags.

**Comment by meetinghouse** [comment]
Thanks. The unused tags are gone now. We can restrict ourselves to alphanumeric characters in tags, no problem. I don't know why it didn't occur to me that the plus sign was causing the problem. As for the left nav overflowing the page, it isn't now, but I don't know what to do in future if it does. It is not critical at present, but may become a problem again...

**Comment by acavanagh** [comment]
The tag area in the left nav should also now scroll in case it gets
overloaded again

**Comment by meetinghouse** [comment]
Oh, that is great. Thanks.
