### ISSUE TITLE
Dark theme: Widen left nav

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#203]
The space between the left nav bar and the main page content can be shrunk by about 60% (meaning, it should be about 40% the space it is now). Please do this by widening the left nav toward the right rather than moving the main content to the left. That way each line on the left nav can hold more text. The main content should be lined up at the same spot on every page.

The person who is doing the supplemental css changes has indicated he is unable to make this change.

![screenshot 2015-09-10 at 1](https://cloud.githubusercontent.com/assets/5215893/9795495/04d55604-57bf-11e5-8ae5-686d4a4aa968.jpg)

**Comment by meetinghouse** [comment]
I know there are several issues in right now that are marked "High Priority." I just wanted to comment to let you know this one is John's is on the top of the list right now for John. Thanks.

**Comment by meetinghouse** [comment]
As an update, this is still John's top priority for moving forward with the Dark Theme. Thanks.

**Comment by acavanagh** [comment]
is this for all sites using the dark theme?

**Comment by meetinghouse** [comment]
Yes, please.

Sincerely,

Katherine Johnson, Content Developer
The Custom Building & Restoration Trades Directory
<http://www.restorationtradesdirectory.com/>
http://www.restorationtradesdirectory.com
(413) 584-0288

Published by:
Corbett Research Group <https://mail.google.com/>
"Building Websites that Work - - for the Building Artisans."
http://www.restorationtrades.com

**Comment by acavanagh** [comment]
Just had a chance to look at this.  Ironically, it already is as you request.  The problem is the that the grey background image doesn't extend to the end of the sidebar, so that it looks like the sidebar is too short and the body is to wide.  I've attached an image to illustrate - I added a purple background to the sidebar so you can see where it actually ends.  The root problem here is that the grey background element is an image that doesn't extend to the end of the sidebar.  That grey background image is applied in line 6 of the custom css file.

https://www.dropbox.com/s/zm2ggow7eredjoy/Screenshot%202015-09-30%2015.51.53.png?dl=0

**Comment by acavanagh** [comment]
I'm assuming that whoever applied the background measured it to the width of the menu inside the sidebar, and not to the sidebar itself.  Understandable, because the sidebar element is both white on white, so it's hard to see where it ends, and that div has no measurable height because all the elements it contains are floated - makes it easy to miss.

All you really need to do here is make that grey image 295px instead of 244px wide.

**Comment by meetinghouse** [comment]
Got it, thanks. I've sent this information to Dan and have removed the High Priority tag from this issue for now, since it isn't your priority anymore. I'll leave it open until it's resolved, though.

**Comment by meetinghouse** [comment]
Dan's got this fixed up. Thanks for you input, Andy. I'll close it now.
