### ISSUE TITLE
DARK THEME: Left nav not scrollable

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#214]
We are having a problem with the left nav bar overflowing the screen when the Builder's Notebook tags are expanded, but it is not scrollable, so you can't get to the content (or the edit button) that has been pushed off the screen. 

Reference issue #182, the first item in the list. It appears to be the same problem.
![screenshot 2015-11-03 at 1 13 34 pm](https://cloud.githubusercontent.com/assets/5215893/10917039/b6d45020-822c-11e5-940b-0afddcf68c51.png)

**Comment by jboz62** [comment]
The left sidebar is set to "position: fixed" in the stylesheet. To make the left sidebar scroll with the page, the style just needs to be changed to "position: relative". 

However, you can get ride of the large gap between the sidebar and the content and remove the padding that is there so that the menu items are not wrapping onto the next line. That saves a lot of space and may alleviate this problem without having to make the menu scroll. See screenshot:

![screen shot 2016-01-14 at 10 02 48 pm](https://cloud.githubusercontent.com/assets/11739120/12344504/d54536c4-bb0b-11e5-8318-89b273397e09.png)

**Comment by jboz62** [comment]
We could also reduce the font size and line height on the sub-menu items to reduce the amount of space they take up, that would help too (like we did on S+H). That would look like this:

![screen shot 2016-01-14 at 10 15 44 pm](https://cloud.githubusercontent.com/assets/11739120/12344552/6e6a222e-bb0c-11e5-9628-9c692f3275de.png)

**Comment by jboz62** [comment]
Here it is in the admin view:
![screen shot 2016-01-14 at 10 21 06 pm](https://cloud.githubusercontent.com/assets/11739120/12344633/4596842c-bb0d-11e5-9934-016a31948ecd.png)

**Comment by meetinghouse** [comment]
I think it is important that the left nav scrolls because inevitably it will be needed by somebody or other. I'm marking this issue as medium priority now, but I did want to provide a response.

**Comment by jboz62** [comment]
This is a simple fix that Katherine can deploy, just add:

```
.sidebar-nav {
    position: relative !important;
}
```
into the custom CSS file. However, not sure I'd do that for ALL the sites as it lessens the user experience by hiding the menu when you scroll down. Also, it just doesn't look as good visually. I would only do this on an **as-needed** basis. It's a 15 second fix, so you can quickly add it to sites that are having trouble with that. S+H, for example, probably doesn't need this, but not sure. That's my humble opinion, you might have some other ideas about it.

**Comment by meetinghouse** [comment]
Great, John, thanks. I pasted that little snippet into the CustomProject.css file for the testdeploy site and it seems to work just fine. I'll close this one now. Thanks.
