### ISSUE TITLE
FORGE: Turning off debugger

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#233]
I just want to put this into GitHub so if I need to refer to it later I can. John B, you noted that in some of the error messages Forge was throwing out when trying to deploy last week, there was a recommendation to turn off the debugger.

You also told me I could do that in the GitHub Code files at this path:

app/config/app.php 

on line 16, change true to false.

I can do that and it shouldn't be a problem, but I just want to document it and make sure it is not going to mess anyone up if I do that. Barry? Andy?

**Comment by KathJohnson** [comment]
Note: John B. has said this is not the right way to turn off this debugger. Standing by for updated information.

**Comment by jboz62** [comment]
You can find the method here: https://laracasts.com/discuss/channels/forge/disable-xdebug <https://laracasts.com/discuss/channels/forge/disable-xdebug>

You’ll need to run some commands via ssh and you’ll need the password for the server. I tried to run it, but ran into the password prompt. I tried the password for forge access, but that’s not it.

The first command:
sudo php5dismod debug

The second command:
sudo service php5-fpm restart

Let me know if you need any assistance on this.

John

**Comment by jboz62** [comment]
Katherine,

We may need to contact support at Forge if we don’t have the password for the server and have them turn off the xdebug for us. Let me know what the status is on this please.

Thanks,
John

**Comment by meetinghouse** [comment]
John,

I think I have the password for the server. It's the password I use to
login through PuTTY and change the site config when launching a sample site
as a live site. The only problem is that I really don't know what I'm doing
in there and in order to make changes without botching things, I have to
have super duper step-by-step instructions.

I could give you the password instead if you want. The one I've used a
gnarly one that starts with "u". Do you have that one?

Sincerely,
Katherine Johnson, Research Director
Corbett Research Group
http://www.restorationtrades.com
"Web Marketing that Works"

Publishers of:

The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

The Building Arts Notebook, "Journal of the Guild of Building Artisans"
http://buildingartisansguild.com/

Email:  katherine@restorationtrades.com
Phone: (413) 475-3154

**Comment by jboz62** [comment]
Yes, please. If you want to send it in a separate email to my address, might be best. That looks to be a pretty easy change to make via ssh, so I can run it to switch that off.

Any word on the access to git for Sudhir? He’s ready to commit the changes for the menu.

Thanks,
John
--
John Bozaan
Bozaan Design
413-437-0097
www.bozaandesign.com <http://www.bozaandesign.com/>

**Comment by meetinghouse** [comment]
Yes, it's a powerful password, so I will send it separately. Subject line
will be "Gnarly" because it is. Also, I like the word gnarly.

Sincerely,
Katherine Johnson, Research Director
Corbett Research Group
http://www.restorationtrades.com
"Web Marketing that Works"

Publishers of:

The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

The Building Arts Notebook, "Journal of the Guild of Building Artisans"
http://buildingartisansguild.com/

Email:  katherine@restorationtrades.com
Phone: (413) 475-3154

**Comment by jboz62** [comment]
Hah, me too. Thanks!

**Comment by jboz62** [comment]
That should be off now, Katherine. Next deploy you run you can double check that.

**Comment by KathJohnson** [comment]
Great. Code deployment to weatherstrippingkit on 4-13-16 went smoothly and did not result in the xdebugger warning, so I think we're good. Closing.
