### ISSUE TITLE
BOTH THEMES: Error when setting Portfolio Menu Position

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#242]
@1sp @jboz62 With the updated ability to set pages as menu items, I find that "Portfolios" does not show up in the menu at all. I went to the Admin Settings page to set the Portfolio Menu Position, thinking that might make it show, but I got an error screen when I hit "Update" on the Settings. Screenshot attached.

![error upon updating portfolio menu position](https://cloud.githubusercontent.com/assets/5922040/14892767/54214f20-0d3a-11e6-875a-f413e9ff96bc.png)

**Comment by jboz62** [comment]
It looks like the database wasn’t updated to add the new column: General error: 1 no such column: portfolio_menu_postion

**Comment by jboz62** [comment]
did the script run a php artisan migrate?

**Comment by KathJohnson** [comment]
Yes, php artisan migrate is in there.

**Comment by 1sp** [comment]
I added a migration which creates this data column in the mentioned table. Please run it and the error will disappear

**Comment by jboz62** [comment]
It looks like the install script does have “php artisan migrate” in it, doesn’t that run the migration, Sudhir?

**Comment by 1sp** [comment]
Yes, it does. Is it possible to see laravel logs to check whether something failed during the deployement?

**Comment by jboz62** [comment]
It doesn’t look to have failed, it says it migrated the table:
![screen shot 2016-04-28 at 1 02 28 pm](https://cloud.githubusercontent.com/assets/11739120/14894433/aa5c857e-0d41-11e6-9652-ceca193b92ad.png)

**Comment by jboz62** [comment]
Thu Apr 28 11:33:10 EDT 2016
Already on 'i221'
Your branch is up-to-date with 'origin/i221'.
From github.com:meetinghouse/cms
 * branch            i221       -> FETCH_HEAD
Already up-to-date.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Generating autoload files
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader
> php artisan cms:setup
Migrated: 2016_04_07_101858_add_portfolio_coloumn_to_settings_table

**Comment by meetinghouse** [comment]
OK, since you say it should be in there, I just re-deployed to the menus
site through Forge just to see if there's any possibility that there was a
change since yesterday. I guess there was, because now I'm able to set the
Portfolio Menu Position without getting an error. There is still a problem
with it, but I will open separate issue so as not to confuse things. If you
concur that this is resolved, please close.

Sincerely,
Katherine Johnson, Research Director
Corbett Research Group
http://www.restorationtrades.com
"Web Marketing that Works"

Publishers of:

The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

The Building Arts Notebook, "Journal of the Guild of Building Artisans"
http://buildingartisansguild.com/

Email:  katherine@restorationtrades.com
Phone: (413) 475-3154

**Comment by 1sp** [comment]
From the logs it looks like the migration has run successfully. John, you had the same issue until you did the artisan migrate and it disappeared. Can this is replicated one more time on new test site ?

**Comment by jboz62** [comment]
Sudhir, were you asking if Katherine could re-deploy this onto another test site? I'm sure she could do that, if you'd like verification that all is working right.

**Comment by KathJohnson** [comment]
OK, I created a new test site, and was able to NOT get an error when setting Portfolio Menu Position. So I think this specific issue is resolved. I'm closing it.
