### ISSUE TITLE
S+H: Read More link on Builder's Notebook page

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#262]
@jboz62 

I don't know if this is a css change or needs to be an underlying code base change, but S+H has asked for a "Read More" link to appear on the Builder's Notebook page under each entry so it is clear that there is more to read.

They'd like some white space between the end of the content and the link, and for the link to be distinguishable as a link (they said blue, but perhaps underlined would be more harmonious with the page design). They'd like it to appear in parentheses, and link, of course, to the full blog post page.

**Comment by jboz62** [comment]
It’s possible to do this via css, but not the best solution. The problem is, you can add a “read more” in the "Intro Paragraph” excerpt text box to have it show up in the listing, but it also shows up when you navigate to the full page. You would need to hide it on the full page and display it in the listing. It would be best to do that in the code so that it would have the same link that is around each entry in the post listing.

In order to do this client side, we’d need to add the “read more” and use the source button to add a css class to it (like: <p><a class="read-more" href="Historic_Roxbury_Puddingstone">Read More</a></p>) then I could use a script to display or hide it depending on the URL. Of course, that probably requires a deployment, though.

Since we have a bottleneck going on with deployment, that’s not possible right now. 

Is Sudhir looking into how the “builder’s notebook” menu setup works and how to incorporate it into the master repository (blog)? I’m not sure how we can deploy to S+H with all the custom code that seems to be in there. That needs to be figured out before we can do anything with S+H, along with the whole deployment issue in general.

Best,
John
--
John Bozaan
Bozaan Design
413-437-0097
www.bozaandesign.com <http://www.bozaandesign.com/>

**Comment by jboz62** [comment]
There are a couple nice solutions for this out there, but both would require we either take the code further out of version control, or do this after we fix the menu/blog issue and deploy to S+H.

This might be a good solution for this: http://jedfoster.com/Readmore.js/
Here's another that would work for this: https://codepen.io/maxds/pen/jgeoA/

**Comment by jboz62** [comment]
@vivek-chaudhari Vivek, we have a "read more..." feature on the related projects, [see here](http://klitsas.corbettresearchgroup.com/structural_restoration). We need this to also be on the blog page. Can you look at how that was done and let me know if you can add it to the blog? S+H wants this on their ["Builder's Notebook"](http://shconstruction.com/posts) (blog). Please give me a time estimate on this. Thanks, John

**Comment by jboz62** [comment]
@vivek-chaudhari It looks like that code for the "read more" is in: cms/app/views/shared/projects_teasers.blade.php

Hope that helps.

**Comment by jboz62** [comment]
@vivek-chaudhari Vivek, here are a couple images to show you what we need:

This is in the post edit/create view:
![blog-post](https://cloud.githubusercontent.com/assets/11739120/19584451/92af0554-9712-11e6-8106-0aa45c6aa0f4.jpg)

The front end blog:
![blog-listing](https://cloud.githubusercontent.com/assets/11739120/19584454/9767d7a6-9712-11e6-98d5-fe5b7a2203fb.jpg)

**Comment by vivek-chaudhari** [comment]
@jboz62  we can easily achieve this, no need to use css or any other external js library. we can do this in php. I will take 1-1.5 hours to do this.

**Comment by jboz62** [comment]
@vivek-chaudhari Yes, those were old notes, we don't need css or js, just in the code base. Please execute this change. Thanks.

**Comment by vivek-chaudhari** [comment]
@jboz62 I will proceed for changes and give you update soon.

**Comment by vivek-chaudhari** [comment]
@jboz62 Now please review this.

**Comment by jboz62** [comment]
@vivek-chaudhari I've been out sick, Vivek, still recovering but will begin getting back to work. Sorry for the delay.

**Comment by vivek-chaudhari** [comment]
@jboz62 It's okay John, Hope you will get well soon.Whenever we need to go on then let me inform.

**Comment by jboz62** [comment]
@vivek-chaudhari Vivek, the "read more" looks good, but it's in the wrong place. Please review the screenshot below for the proper placement and revise. Thank you.
![9767d7a6-9712-11e6-98d5-fe5b7a2203fb](https://cloud.githubusercontent.com/assets/11739120/20182505/fb8adc2e-a72f-11e6-9528-3e7c7d406dc5.jpg)
![read-more2](https://cloud.githubusercontent.com/assets/11739120/20182888/54f14eb4-a731-11e6-94cb-32f5fd12a032.jpg)

**Comment by vivek-chaudhari** [comment]
@jboz62 Okay john I can do this.

**Comment by vivek-chaudhari** [comment]
@jboz62 Now review this.

**Comment by jboz62** [comment]
Finished.
