### ISSUE TITLE
Update help for new content

### ISSUE THREAD

**Issue by acavanagh** [meetinghouse/cms#40]
A lot of the help links for the new content (All of the blog post fields and the Tags on projects) are outdated or wrong.  I'm not totally clear on how your managing the help - we should have a quick conversation about this and hash out who's updating what when.

**Comment by meetinghouse** [comment]
I already started banging on about this in Issue #45, sorry, since that one is actually closed. 

The links to the existing help page (which do need to be updated, for sure) are currently set in the cms_help repository. I can update them there, but I don't know how to make the help different for the dark theme and light theme.

**Comment by acavanagh** [comment]
if you can tell me which help links should be different and what they should link to in the dark theme I can adjust them.

**Comment by acavanagh** [comment]
I'm going to close this, since there is another active issue on the same topic.
