### ISSUE TITLE
Add ability to sort images on Portfolio page

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#41]
Per your answer to my question in issue #21 , please add the ability to sort the image tiles as they appear on the portfolio page, http://cms.zigbop.io/portfolio.
![1](https://cloud.githubusercontent.com/assets/5215893/5944148/b555d7ac-a6f2-11e4-9510-b1c0467b5e2e.png)They currently sort by date added, which is not editable. It could be made editable, I suppose, but it would be better to make it possible for the images to be deliberately sorted.

I am not sure how best to do this, as the Portfolio page itself is not editable. There used to be a sort order drop-down in the project edit screen which was removed as part of issue issue #30 . As I stated in that issue, I don't know the exact functionality of that, but some way to sort the projects should be available.

If it is possible to add it to the Portfolio screen, please do so. If it is more feasible to add it to the project edit screen, then please put it there.

**Comment by acavanagh** [comment]
I put the order field back and set the index and the tags index to order the projects by that field.  Because projects can belong to multiple categories, this is more of a 'weight' than an 'order' field - projects with a lower weight will rise to the top of the page, projects with a higher weight will sink toward the bottom of a page.  If you have two projects in the same category with the same order number, they'll be next to each other.
