### ISSUE TITLE
Enable publishing website.

### ISSUE THREAD

**Issue by meetinghouse** [meetinghouse/cms#73]
Permit website http://libertyconstruction.corbettresearchgroup.com/ to publish. Currently produces error, "Will return shortly".  (??)

WE THINK this means that (1.) we have created this website, but that (2.) it won't publish because of an "unpublish" setting or checkbox, somewhere. 

If we are right on both counts, please enable the website to publish.

**Comment by acavanagh** [comment]
The website it's in maintenance mode. Last week either John or Katherine
asked that I set new sites to start in maintenance mode. Do you want that
change reversed now?

**Comment by acavanagh** [comment]
The ticket where you requested making maintenance mode the default it #53.  I just logged in and turned off maintenance mode for libertyconstruction. Do you want me to revert the change for #53 so that maintenance mode is not longer the default?

For future reference, to turn off maintenance mode you just have to login at /login and then turn off maintenance mode at the admin settings page.

**Comment by meetinghouse** [comment]
We don't want Maintenance Mode to make a site unvisitable. It only should tell Google robots to go away.

Is it reasonable to change what the Maintenance Mode setting is, so it is merely a robot.txt file change? I really have no idea how flexible this is.

**Comment by acavanagh** [comment]
I don't either, honestly - it was set up before my time.  I'll look into it
when I make the other requested changes tonight.  It might be a quick fix.

**Comment by meetinghouse** [comment]
I think this can be closed, as this request is not really needed. We have simply adapted to the way maintenance mode works now.
